### ISSUE TITLE
FR5. Search Box

### ISSUE THREAD

**Issue by lgipsonbb8648** [WSU-4110/Swap-Book#12]
|FR5. Search Box|
|---|
|**Goal**: To be able to search books. |
**Stakeholders:** Wayne State University students/faculty, Developer team |
| **Description:** When the user wants to search a book, the requirement will allow him/her to search by either book name, ISBN, or author.|
| **Origin:** Based on initial project specification document, team members came up with this description during the first meeting.|
| **Version:** 1.0  |  
|**Date:** 09/05/2019  
|  **Priority:** 1 |

**Comment by MahdiBazyar** [comment]
one of the features to work on during the first sprint
